packages/nextjs/app/lending/components/AssetsToSupply.tsx
packages/nextjs/app/lending/components/modals/BorrowTransactionModal.tsx
packages/nextjs/app/lending/components/modals/RepayTransactionModal.tsx.tsx
packages/nextjs/app/lending/components/modals/SupplyTransactionModal.tsx
packages/nextjs/app/lending/components/modals/WithdrawTransactionModal.tsx
packages/nextjs/hooks/useGetReservesData.ts
packages/nextjs/utils/toWeiConverter.ts

- Implemented functionality of useApproval hook for proper operation of Repay and Supply features.
- Created a general function 'ConverterToWei' to transform inputs correctly according to the asset's decimal places.

fix (modals): fix Repay and Supply modals to implement useApproval hook

---

packages/nextjs/app/cdp/components/modals/DepositModal.tsx
packages/nextjs/app/cdp/components/modals/WithdrawModal.tsx
packages/nextjs/app/cdp/components/tables/DepositTable.tsx
packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx

Fixed input validation both in Liquidity and in CDP (Deposit and Withdrawal Modals)

Liquidity + Hot Fixes

---

packages/nextjs/app/liquidity/components/LiquidityInfo/index.tsx

Adjusted Tailwind to cater to smaller devices

Mobile Hot Fix

---

packages/nextjs/app/cdp/components/modals/DepositModal.tsx
packages/nextjs/app/cdp/components/modals/WithdrawModal.tsx

Adding MAX buttons on Modals

---

packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx

Added MAX buttons to LiquidityWidget

---

packages/nextjs/components/Header.tsx

Making it more accesible to everyone.

added Liquidity tab to Header

---

packages/nextjs/app/cdp/components/CDPStats.tsx
packages/nextjs/app/cdp/components/modals/DepositModal.tsx
packages/nextjs/app/cdp/components/modals/MintModal.tsx
packages/nextjs/app/cdp/components/modals/RepayModal.tsx
packages/nextjs/app/cdp/components/tables/DepositTable.tsx
packages/nextjs/app/cdp/components/tables/YourDeposits.tsx

CDP Mobile Formatting

---

packages/nextjs/app/lending/components/AssetsToSupply.tsx
packages/nextjs/app/lending/components/ProfileStats.tsx
packages/nextjs/app/lending/components/YourBorrows.tsx
packages/nextjs/app/lending/components/YourSupplies.tsx
packages/nextjs/app/lending/page.tsx

Modified Lending page for Mobile viewing

---

packages/nextjs/app/cdp/components/tables/DepositTable.tsx
packages/nextjs/app/liquidity/components/LiquidityInfo/index.tsx
packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx
packages/nextjs/app/liquidity/components/OverviewWidget/index.tsx

No habia tenido tiempo de agregar errores para guiar mejor al usuario, aqui añadí que cuando el chain es Polygon o BSC, se muestre un error para cambiar a Base.

Added network error & margins fixes

---

packages/nextjs/app/components/FeaturesTab/FeaturesTabItem.tsx
packages/nextjs/app/privacy/page.tsx
packages/nextjs/app/terms/page.tsx
packages/nextjs/components/Footer.tsx

So that it can be added to Base Ecosystem

Added Terms of Service and Privacy Notice

---

packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx
packages/nextjs/components/Header.tsx

Changed HEader names and still working in Liquidity Widget

Experimenting

---

packages/nextjs/app/cdp/components/CDPStats.tsx
packages/nextjs/app/utils/utils.ts

Centralize chain logic for CDP component

---

packages/nextjs/app/lending/components/modals/SupplyTransactionModal.tsx
packages/nextjs/hooks/useSupply.ts

Approve and re-fetch seem to be stable

---

package.json
packages/nextjs/app/lending/page.tsx
packages/nextjs/stores/lending-store.ts
yarn.lock

Add zustand and move first piece to global state: reserveData

---

packages/nextjs/app/lending/components/AssetsToBorrow.tsx
packages/nextjs/app/lending/components/ReserveAssetInfo.tsx
packages/nextjs/app/lending/components/YourBorrows.tsx

Just some touch-ups on copy and CSS.

UI Refinements

---

packages/nextjs/app/cdp/page.tsx
packages/nextjs/stores/minting-store.ts

created a new zustand store called minting-store where I will be adding more and more states that are spread out throughout the cdp components. This is just the 1st step.

adding new store to keep global cdp state

---

packages/nextjs/app/streams/components/Flows/index.tsx
packages/nextjs/app/streams/components/index.tsx
packages/nextjs/app/streams/page.tsx

This is to expand XOC's capabilties using the Superfluid protocol. A SuperXOC token already exists on Base and Polygon and I just want to put a frontend to it inside our application.

Embarking on new Streams Page

---

packages/nextjs/app/streams/components/WalletStats/index.tsx
packages/nextjs/app/streams/page.tsx
packages/nextjs/stores/streaming-store.ts

Added WalletStats so the user has more data about his streams. next steps are adding a new widget that shows all active (maybe past) streams.

Kept adding to the Streams page

---

packages/nextjs/components/Header.tsx

Still partners to be added and edited. Any suggestions please bring them forward in the Telegram channel.

added ecosystem tab

---

package.json
packages/nextjs/app/locales/mx/common.json
packages/nextjs/app/streams/components/ActiveStreams.tsx
packages/nextjs/app/streams/page.tsx
yarn.lock

WalletConnect was not generting a login qrcode, updated version of RainbowKit to hopefully patch it"

WalletConnect & RainbowKit Update

---

packages/nextjs/app/lending/components/ReserveAssetInfo.tsx
packages/nextjs/app/lending/components/modals/BorrowTransactionModal.tsx
packages/nextjs/app/lending/components/modals/WithdrawTransactionModal.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json

Added a bunch of checks and UI refinements to prevent errors i.e. "Can'T withdraw because there is no availableLiquidity" and added the cap progress bars in the ReserveAssetInfo.tsx component.

Alux Refinements

---

package.json
packages/nextjs/app/lending/components/ReserveAssetInfo.tsx
packages/nextjs/app/lending/page.tsx
yarn.lock

Main thing this push does is add driver to get new users guided through the app. 
Also added a couple small tooltips in the caps progress bars to give more context on them, still have to add the i18n of all of it.

Added Driver.JS to Guide Users through Alux & More

---

packages/nextjs/app/streams/page.tsx

Almost done with 1st step, now need to figure out how to integrate Superfluid's Subgraph to pull outgoing/incoming flows.

Streams CSS refinement

---

packages/nextjs/app/lending/components/AssetsToBorrow.tsx
packages/nextjs/app/lending/components/AssetsToSupply.tsx
packages/nextjs/app/lending/components/BalanceOf.tsx
packages/nextjs/app/lending/components/ProfileStats.tsx
packages/nextjs/app/lending/components/YourBorrows.tsx
packages/nextjs/app/lending/components/YourSupplies.tsx
packages/nextjs/app/lending/page.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json
packages/nextjs/stores/lending-store.ts

Added it in all major components.

Added Empty State if Wallet Not Connected in Alux

---

packages/nextjs/app/lending/components/APYGraph.tsx
packages/nextjs/app/lending/components/AssetsToBorrow.tsx
packages/nextjs/app/lending/components/AssetsToSupply.tsx
packages/nextjs/app/lending/components/ReserveAssetInfo.tsx
packages/nextjs/app/lending/components/YourBorrows.tsx
packages/nextjs/app/lending/components/YourSupplies.tsx
packages/nextjs/app/lending/components/modals/BorrowTransactionModal.tsx
packages/nextjs/app/lending/page.tsx

Mainly adjusted for mobile screens, some column and currency adjustments and tour button polishing.

Mobile Adjustments for Alux

---

packages/nextjs/app/lending/components/APYGraph.tsx
packages/nextjs/app/lending/components/AssetsToSupply.tsx
packages/nextjs/app/lending/components/YourSupplies.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json

Added tooltip to CETES to inform users about the extra-yield provided by Etherfuse.

CETES Tooltip

---

packages/nextjs/app/components/hero.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json
packages/nextjs/components/Header.tsx

Updated hero with new action ader with simpler terms.

Header and Hero Update

---

packages/nextjs/app/streams/page.tsx

cursor optimizations helped me size the mobile screen much better.

optimized streams for mobile screens

---

packages/nextjs/app/liquidity/components/ContractLinks.tsx
packages/nextjs/app/liquidity/components/PriceChart.tsx
packages/nextjs/app/liquidity/components/PriceMetrics.tsx
packages/nextjs/app/liquidity/page.tsx
packages/nextjs/app/utils/mockData.ts

Included new widget for checking out PriceMetrics of the popol, a link to every contract involved and a pricechart which is a WIP, only mocked data in it. Have to smooth out the old components here but the new ones already provide utility.

revamping liquidity page

---

packages/nextjs/app/liquidity/components/ContractLinks.tsx
packages/nextjs/app/liquidity/components/LiquidityCards.tsx
packages/nextjs/app/liquidity/components/LiquidityInfo/index.tsx
packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx
packages/nextjs/app/liquidity/components/PriceChart.tsx
packages/nextjs/app/liquidity/components/PriceMetrics.tsx
packages/nextjs/app/liquidity/page.tsx

Added some new components to visualize key info about the pool of USDC/XOC, I'll let copilot describe more about it.

Liquidity Page Harmonization

---

packages/nextjs/app/lending/components/modals/BorrowTransactionModal.tsx
packages/nextjs/app/lending/page.tsx
packages/nextjs/hooks/useGetUserAccountData.ts
packages/nextjs/services/web3/wagmiConfig.tsx
packages/nextjs/stores/lending-store.ts

There was a type error that was interfering with the propagation of data to the ProfileStats component, especially with Coinbase Wallet it was not functioning correctly, this should patch it up.

patching up wallet issue in ProfileStats.ts

---

packages/nextjs/app/locales/mx/common.json

highlight Base

---

packages/nextjs/app/liquidity/components/PriceChart.tsx
packages/nextjs/hooks/usePriceHistory.ts

Trying to add the spot price to the PriceChart.ts component.

adding new hook to fetch spot price from supabase

---

packages/nextjs/app/components/About/index.tsx
packages/nextjs/app/components/hero.tsx
packages/nextjs/app/directory/page.tsx
packages/nextjs/app/liquidity/components/PriceChart.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json

Mobile optimizations in Landing, Liquidity and Directory pages.
Added a new milestone in Landing, for cbBTC addition.

New Milestones and CSS Refinement

---

packages/nextjs/app/liquidity/components/PriceChart.tsx

just small css change c because the dark mode was pissing me off

fixed background contrast in PriceChart

---

packages/nextjs/app/cdp/components/modals/DepositModal.tsx
packages/nextjs/stores/cdp-store.ts

Started to update and refactor cdp components because they're the oldest ones.

CDP Renovation 

---

packages/nextjs/app/liquidity/components/LiquidityWidget/index.tsx
packages/nextjs/app/locales/en/common.json
packages/nextjs/app/locales/mx/common.json

Received some feedback from Carlos C regarding CDP and Liquidity pages.

user feedback in liquidity widget
